### PR TITLE
8297804: (tz) Update Timezone Data to 2022g

### PR DESCRIPTION
**Pull request by gnu-andrew**
Clean backport of the latest tzdata update.

This pull request contains a backport of commit [ce896731](https://github.com/openjdk/jdk/commit/ce896731d38866c2bf99cd49525062e150d94160) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Andrew John Hughes on 7 Dec 2022 and was reviewed by Naoto Sato.

Tests in java/util/TimeZone, java/time/test, sun/util/calendar, sun/util/resources and sun/text/resources all pass.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297804](https://bugs.openjdk.org/browse/JDK-8297804): (tz) Update Timezone Data to 2022g

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u pull/361/head:pull/361` \
`$ git checkout pull/361`

Update a local copy of the PR: \
`$ git checkout pull/361` \
`$ git pull https://git.openjdk.org/jdk17u pull/361/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 361`

View PR using the GUI difftool: \
`$ git pr show -t 361`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u/pull/361.diff">https://git.openjdk.org/jdk17u/pull/361.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Interestingly the PR bot does not recognize the backport as clean. Seems like some files have been moved between head and here which was no issue for the /backport command on the commit in head. Nevermind, I eyeballed it and it looks correct.

**Comment by gnu-andrew** [comment]
> Interestingly the PR bot does not recognize the backport as clean. Seems like some files have been moved between head and here which was no issue for the /backport command on the commit in head. Nevermind, I eyeballed it and it looks correct.

Strange. The `/backport` command seems to have handled both 17u & 11u fine. Thanks for the review.

I've already flagged this with `jdk17u-critical-request` if you'd like to approve.

**Comment by gnu-andrew** [comment]
Thanks.

/integrate

**Pull request closed without merging**
