### PR TITLE
8273235: tools/launcher/HelpFlagsTest.java Fails on Windows 32bit

### PR DESCRIPTION
**Pull request by adamfarley**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8273235](https://bugs.openjdk.java.net/browse/JDK-8273235): tools/launcher/HelpFlagsTest.java Fails on Windows 32bit

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u pull/274/head:pull/274` \
`$ git checkout pull/274`

Update a local copy of the PR: \
`$ git checkout pull/274` \
`$ git pull https://git.openjdk.java.net/jdk17u pull/274/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 274`

View PR using the GUI difftool: \
`$ git pr show -t 274`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u/pull/274.diff">https://git.openjdk.java.net/jdk17u/pull/274.diff</a>

</details>

### CODE REVIEW

**Comment by adamfarley** [comment]
Sponsor requested please.

**Comment by RealCLanger** [comment]
As stated in the jdk11u PR, please request JDK17 backport approval via jdk17u-fix-request label in the JBS bug.

**Comment by adamfarley** [comment]
Will do. :)

**Comment by shipilev** [comment]
Push approval (`jdk17u-fix-yes`) is there now, I am sponsoring.

/integrate

**Comment by adamfarley** [comment]
Thanks @shipilev :)

**Pull request closed without merging**
