### PR TITLE
8277529: SIGSEGV in C2 CompilerThread Node::rematerialize() compiling Packet::readUnsignedTrint

### PR DESCRIPTION
**Pull request by fmatte1**
JDK-8277529
SIGSEGV in C2 CompilerThread Node::rematerialize() compiling Packet::readUnsignedTrint

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8277529](https://bugs.openjdk.java.net/browse/JDK-8277529): SIGSEGV in C2 CompilerThread Node::rematerialize() compiling Packet::readUnsignedTrint

### Reviewers
 * [Tobias Hartmann](https://openjdk.java.net/census#thartmann) (@TobiHartmann - **Reviewer**)
 * [Christian Hagedorn](https://openjdk.java.net/census#chagedorn) (@chhagedorn - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u pull/322/head:pull/322` \
`$ git checkout pull/322`

Update a local copy of the PR: \
`$ git checkout pull/322` \
`$ git pull https://git.openjdk.java.net/jdk17u pull/322/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 322`

View PR using the GUI difftool: \
`$ git pr show -t 322`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u/pull/322.diff">https://git.openjdk.java.net/jdk17u/pull/322.diff</a>

</details>

### CODE REVIEW

**Review by TobiHartmann — APPROVED** [review]
Looks good.

**Comment by fmatte1** [comment]
Thanks, Tobias for the review.

**Review by chhagedorn — APPROVED** [review]
Looks good!

**Pull request closed without merging**
