### PR TITLE
8273595: tools/jpackage tests do not work on apt-based Linux distros like Debian

### PR DESCRIPTION
**Pull request by theaoqi**
The patch applies clean. Low risk, only test changes. `test/jdk/tools/jpackage` tests passed on x64/Ubuntu and x64/Debian.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8273595](https://bugs.openjdk.java.net/browse/JDK-8273595): tools/jpackage tests do not work on apt-based Linux distros like Debian

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u pull/219/head:pull/219` \
`$ git checkout pull/219`

Update a local copy of the PR: \
`$ git checkout pull/219` \
`$ git pull https://git.openjdk.java.net/jdk17u pull/219/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 219`

View PR using the GUI difftool: \
`$ git pr show -t 219`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u/pull/219.diff">https://git.openjdk.java.net/jdk17u/pull/219.diff</a>

</details>

### CODE REVIEW

**Comment by theaoqi** [comment]
jdk17u-fix-request had been approved. Could someone please sponsor this backport?

/integrate

**Comment by shipilev** [comment]
@theaoqi Please reschedule the GHA runs, so they are provably green? Probably merge from jdk17u master too. Then I'll sponsor.

**Comment by theaoqi** [comment]
@shipilev, master has been merged. GHA tests are retriggered and passed. If I was doing correctly, please sponsor. Thanks!

/integrate

**Comment by theaoqi** [comment]
Thanks again for the help, @shipilev.

**Pull request closed without merging**
