### PR TITLE
8292260: [BACKOUT] JDK-8279219: [REDO] C2 crash when allocating array of size too large

### PR DESCRIPTION
**Pull request by jerboaa**
PR to backout the change of [JDK-8279219](https://bugs.openjdk.org/browse/JDK-8279219). I'll change this to the proper backport title once JDK 19 backout is done.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8292260](https://bugs.openjdk.org/browse/JDK-8292260): [BACKOUT] JDK-8279219: [REDO] C2 crash when allocating array of size too large

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u pull/350/head:pull/350` \
`$ git checkout pull/350`

Update a local copy of the PR: \
`$ git checkout pull/350` \
`$ git pull https://git.openjdk.org/jdk17u pull/350/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 350`

View PR using the GUI difftool: \
`$ git pr show -t 350`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u/pull/350.diff">https://git.openjdk.org/jdk17u/pull/350.diff</a>

</details>

### CODE REVIEW

**Review by RealCLanger — APPROVED** [review]
Looks good. JDK-8284369 is backouted by this as well but that was a specific fix for/after JDK-8279219 anyway.

**Comment by jerboaa** [comment]
@erikj79 @kevinrushforth Would either of you know why we didn't get a `17.0.4.1` backport bug for this? Similar issue to https://github.com/openjdk/jdk11u/pull/49#issuecomment-1214976726 ?

**Comment by erikj79** [comment]
(I don't currently have any github notifications turned on so tagging me doesn't help)
The reason this commit hasn't been notified to JBS is that Skara is currently choking on a tag that was updated/changed in this repo. A fix for that is currently on review in SKARA-1355. I will manually go and get this unstuck for now.

**Comment by RealCLanger** [comment]
Thanks. I already thought, force-pushing the tag would cause trouble somehwere. But it seems like in this case it helps to get the tooling more robust 😄 
One other thing I noted: The backport for 17.0.4.1 now mentions "Resolved in build: master". However, the b01 tag was already set, so it should be b01. Is that an expected outcome due to working on another branch in the repo? Or because 17.0.5 tags are already in place as well?

**Comment by jerboaa** [comment]
> One other thing I noted: The backport for 17.0.4.1 now mentions "Resolved in build: master". However, the b01 tag was already set, so it should be b01.

Fixed this manually. Still interested to hear why that didn't work.

**Pull request closed without merging**
