### PR TITLE
8266510: Nimbus JTree default tree cell renderer does not use selected text color

### PR DESCRIPTION
**Pull request by akashche**
This is a clean backport of the JTree nodes text color fix, I intend to follow up with backporting JDK-8271315.

Testing: checked manually on Linux, Windows and Mac with SwingSet2 that JTree node text color is black without the patch and is correct with the patch.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8266510](https://bugs.openjdk.java.net/browse/JDK-8266510): Nimbus JTree default tree cell renderer does not use selected text color

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u pull/140/head:pull/140` \
`$ git checkout pull/140`

Update a local copy of the PR: \
`$ git checkout pull/140` \
`$ git pull https://git.openjdk.java.net/jdk17u pull/140/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 140`

View PR using the GUI difftool: \
`$ git pr show -t 140`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u/pull/140.diff">https://git.openjdk.java.net/jdk17u/pull/140.diff</a>

</details>

### CODE REVIEW

**Comment by akashche** [comment]
Gentle reminder, it would be great if someone can review this backport.

**Comment by phohensee** [comment]
Clean backports don't need review. Just tag the JBS issue.

**Comment by akashche** [comment]
Marked the bug for approval.

**Pull request closed without merging**
