### PR TITLE
8276025: Hotspot's libsvml.so may conflict with user dependency

### PR DESCRIPTION
**Pull request by sviswa7**
Clean backport to fix the conflicts with libsvml.so distributed with Intel's MKL library.

Best Regards,
Sandhya

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8276025](https://bugs.openjdk.java.net/browse/JDK-8276025): Hotspot's libsvml.so may conflict with user dependency

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk17u pull/250/head:pull/250` \
`$ git checkout pull/250`

Update a local copy of the PR: \
`$ git checkout pull/250` \
`$ git pull https://git.openjdk.java.net/jdk17u pull/250/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 250`

View PR using the GUI difftool: \
`$ git pr show -t 250`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk17u/pull/250.diff">https://git.openjdk.java.net/jdk17u/pull/250.diff</a>

</details>

### CODE REVIEW

**Comment by sviswa7** [comment]
@vnkozlov Could you please review and approve. This is a clean backport but somehow the bot hasn't applied the clean label.

**Comment by vnkozlov** [comment]
@sviswa7 You need to integrate it first as you did for 8273450.
I also need to test it together with closed changes as I did for JDK 18. After everything is good I will sponsor it together with closed part.

**Comment by sviswa7** [comment]
@vnkozlov Thanks, I followed the same steps as for 8273450.  (https://wiki.openjdk.java.net/display/JDKUpdates/How+to+contribute+a+fix)

**Comment by vnkozlov** [comment]
Hmm. In 8273450 I see Bot's comment:
`@openjdk openjdk bot added backport  clean  labels 23 hours ago`

But for some reasons current changes are not treated as clean by Bot:
`@openjdk openjdk bot added the backport  label 2 hours ago`

It asked for review. Okay I will add approval.

**Review by vnkozlov — APPROVED** [review]
Clean backport.

**Comment by vnkozlov** [comment]
Testing passed.

**Comment by sviswa7** [comment]
Thanks a lot @vnkozlov.

**Comment by vnkozlov** [comment]
I pushed closed part too.

**Pull request closed without merging**
