### PR TITLE
8028265: Add legacy tz tests to OpenJDK

### PR DESCRIPTION
**Pull request by alvdavi**
Clean backport of JDK-8028265, bringing timezone tests before updating timezone data to 2022c

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8028265](https://bugs.openjdk.org/browse/JDK-8028265): Add legacy tz tests to OpenJDK

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u pull/353/head:pull/353` \
`$ git checkout pull/353`

Update a local copy of the PR: \
`$ git checkout pull/353` \
`$ git pull https://git.openjdk.org/jdk17u pull/353/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 353`

View PR using the GUI difftool: \
`$ git pr show -t 353`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u/pull/353.diff">https://git.openjdk.org/jdk17u/pull/353.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
Do the tests all pass?

If so, this can go straight to a `jdk17u-fix-request` label on the bug.

**Comment by alvdavi** [comment]
Yes, all test pass. Label added

**Comment by jerboaa** [comment]
> Yes, all test pass. Label added

Since this is for `jdk17u` (October), not `jdk17u-dev` (January), the label ought to be `jdk17u-critical-request`. Please also add a rational to the bug via a "Fix Request" comment next time. Added it for you this time ;-)

**Comment by GoeLin** [comment]
Approved. You can push.

**Comment by phohensee** [comment]
/sponsor

Got the approval.

**Comment by gnu-andrew** [comment]
> > Yes, all test pass. Label added
> 
> Since this is for `jdk17u` (October), not `jdk17u-dev` (January), the label ought to be `jdk17u-critical-request`. Please also add a rational to the bug via a "Fix Request" comment next time. Added it for you this time ;-)

My bad. I realised this morning I'd mentioned the wrong one. Glad to see it's sorted.

**Pull request closed without merging**
