### PR TITLE
8314677: Bump update version for OpenJDK: jdk-17.0.8.1

### PR DESCRIPTION
**Pull request by benty-amzn**
Proposed branch for [JDK-8314677](https://bugs.openjdk.org/browse/JDK-8314677)

Note that the merge preview on this branch will be incorrect as there is no upstream jdk17.0.8 branch, only a 17.0.8-ga tag. As such the PR is based on `master`.
Changes against the GA tag can be viewed at [diff](https://github.com/openjdk/jdk17u/compare/jdk-17.0.8-ga...benty-amzn:jdk17u:jdk17.0.8.1?expand=1)

See also previous discussion on #374

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8314677](https://bugs.openjdk.org/browse/JDK-8314677): Bump update version for OpenJDK: jdk-17.0.8.1 (**Bug** - P4)

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)
 * [Goetz Lindenmaier](https://openjdk.org/census#goetz) (@GoeLin - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk17u.git pull/375/head:pull/375` \
`$ git checkout pull/375`

Update a local copy of the PR: \
`$ git checkout pull/375` \
`$ git pull https://git.openjdk.org/jdk17u.git pull/375/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 375`

View PR using the GUI difftool: \
`$ git pr show -t 375`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk17u/pull/375.diff">https://git.openjdk.org/jdk17u/pull/375.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk17u/pull/375#issuecomment-1686787671)

### CODE REVIEW

**Comment by GoeLin** [comment]
Hi Ben, 

please be careful to push two seperate changes. 
This here already includes the fix. It should only include changes to the two files with the version.
You can make a second PR on top of this one for the real fix.  Just select branch pr/375 as base of the second PR.
Probably you want to wait until the branches are created and you rebased this one on the branch.

Also, I think it is better to use August 24th as date. 
No one will be able to deliver a JVM tomorrow.

Best regards, Goetz.

**Comment by benty-amzn** [comment]
I'm not sure if the jdk17u repo is set up to support dependent PRs - I don't see the expected pr/375 branch available as a base for the fix. I'll create the PR against 17.0.8.1 and wait for this to be integrated first.

**Review by simonis — APPROVED** [review]
Looks good.

**Review by GoeLin — APPROVED** [review]
LGTM

**Pull request closed without merging**
